# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XXb4hUwngU9iJaQcI0D-j6OMmGKmV067
"""

!pip install neulab

from neulab.Algorithms import EuclidMertic

d = {'A': [1, 0, 1, 0, 1, 0], 'C': [1, 1, 0, 1, 1, 0]}
df = pd.DataFrame(data=d)
eqld = EuclidMertic(vector1=df.A, vector2=df.C)
print(eqld)