# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XXb4hUwngU9iJaQcI0D-j6OMmGKmV067
"""

import pandas as pd
data = pd.DataFrame({"birthday" : pd.date_range(start='1/1/1989', end='1/1/2006', periods=100)})
for num, mn in enumerate("January February March April May June July August September October November December".split(), start=1):
    data[mn] = data.birthday.apply(lambda x: int((pd.to_datetime(f'2021-{num}-04 00:00:00') - x).days/365.2 ))
data['year'] = data.birthday.apply(lambda x: x.year)
data.corr().year.sort_values(ascending=False)