# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hgczPIyZ-AytefR1rX3hdJzK1a5PHcmu
"""

import math as mt
import sympy as sym

'''
a = x*w1+w_3
b = x*w2+w_4
'''

def lw():
    # Задаем формулы А и В из данных по Х
    data_x, A, B = [-1, 0, 1], [], []
    for i in data_x:
        if abs(i) == 1:
            A.append('w1+w3') if i > 0 else A.append('-w1+w3')
            B.append('w2+w4') if i > 0 else B.append('-w2+w4')
        else:
            A.append(f'{i}*w1+w3') if i else A.append('w3')
            B.append(f'{i}*w2+w4') if i else B.append('w4')
    # Составляем функцию потерь
    ln1 = f"{sym.log}({mt.e}**({A[0]})/({mt.e}**({A[0]})+{mt.e}**({B[0]})))"
    ln2 = f"{sym.log}({mt.e}**({B[1]})/({mt.e}**({A[1]})+{mt.e}**({B[1]})))"
    ln3 = f"{sym.log}({mt.e}**({A[2]})/({mt.e}**({A[2]})+{mt.e}**({B[2]})))"
    lw = f'-{ln1}-{ln2}-{ln3}'
    print(lw)
    return lw