# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hgczPIyZ-AytefR1rX3hdJzK1a5PHcmu
"""

import sympy as sp
w1, w2, w3, w4 = sp.symbols('w1 w2 w3 w4')

L = -sp.ln(sp.E**(-w1+w3)/(sp.E**(-w1+w3)+sp.E**(-w2+w4))) - sp.ln(sp.E**w4/(sp.E**w3+sp.E**w4)) - sp.ln(sp.E**(w1+w3)/(sp.E**(w1+w3)+sp.E**(w2+w4)))

dLdw1 = sp.utilities.lambdify(
    (w1, w2, w3, w4),
    sp.diff(L, w1),
)
dLdw2 = sp.utilities.lambdify(
    (w1, w2, w3, w4),
    sp.diff(L, w2),
)
dLdw3 = sp.utilities.lambdify(
    (w1, w2, w3, w4),
    sp.diff(L, w3),
)
dLdw4 = sp.utilities.lambdify(
    (w1, w2, w3, w4),
    sp.diff(L, w4),
)


h = 0.1
a_w1 = 0
a_w2 = 0
a_w3 = 0
a_w4 = 0
n = 10

for i in range(0, n + 1):
    print(f'a{i}: ({a_w1}  {a_w2}  {a_w3}  {a_w4})')
    ai_w1 = a_w1 - h * (dLdw1(a_w1, a_w2, a_w3, a_w4))
    ai_w2 = a_w2 - h * (dLdw2(a_w1, a_w2, a_w3, a_w4))
    ai_w3 = a_w3 - h * (dLdw3(a_w1, a_w2, a_w3, a_w4))
    ai_w4 = a_w4 - h * (dLdw4(a_w1, a_w2, a_w3, a_w4))

    a_w1 = ai_w1
    a_w2 = ai_w2
    a_w3 = ai_w3
    a_w4 = ai_w4