# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hgczPIyZ-AytefR1rX3hdJzK1a5PHcmu
"""

import sympy as sp
w0, w1 = sp.symbols('w0 w1')
L = (w0 - w1 - 1)**2 + w0**2 + (w1 + w0 +1)**2 + w0**2 + w1**2

dLdw1 = sp.utilities.lambdify(
    (w0, w1),
    sp.diff(L, w1),
)
dLdw0 = sp.utilities.lambdify(
    (w0, w1),
    sp.diff(L, w0),
)

h = 0.1
a_w0 = 0
a_w1 = 0
n = 10

for i in range(0, n + 1):
    print(f'a{i}: ({a_w0},  {a_w1})')
    ai_w0 = a_w0 - h * dLdw0(a_w0, a_w1)
    ai_w1 = a_w1 - h * dLdw1(a_w0, a_w1)
    a_w0 = ai_w0
    a_w1 = ai_w1